---
kind: Secret
apiVersion: v1
metadata:
  # Since we cannot template values in values.yaml, we hard-code the existing secret name
  name: operators-postgresql-secret
  namespace: {{ .Release.Namespace }}
data:
  # Since Argo Workflow _requires_ the username to be read from a secret, we _have_ to provide one
  postgres-user: cG9zdGdyZXMK
  postgres-password: {{ randAlphaNum 32 | b64enc | quote }}
type: Opaque
