---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-operator
  namespace: operators
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: data
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

  source:
    targetRevision: HEAD
    repoURL: https://github.com/Antfield-Creations/fafa-vae
    path: argo-mlops-operator
