---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operators-postgresql
  namespace: operators
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: operators
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      selfHeal: false
      prune: true

  source:
    targetRevision: HEAD
    repoURL: https://github.com/Antfield-Creations/gke
    path: charts/antfield-postgresql
    helm:
      values: |
        resources:
          requests:
            memory: 64Mi
