---
argo-cd:
  enabled: true

  dex:
    enabled: false

  server:
    extraArgs:
      - --insecure
    ingress:
      enabled: false

  configs:
    repositories:
      antfield-helm-repo:
        url: https://github.com/Antfield-Creations/gke
