---
argo-cd:
  enabled: true

  dex:
    enabled: false

  server:
    extraArgs:
      - --insecure
    ingress:
      enabled: false

    additionalApplications:
      - name: argocd
        namespace: operators
        destination:
          namespace: operators
          server: https://kubernetes.default.svc
        project: default
        source:
          helm:
            valueFiles:
              - values.yaml
          path: charts/argo-cd
          repoURL: https://github.com/Antfield-Creations/gke.git

      - name: argocd-apps
        namespace: operators
        destination:
          namespace: operators
          server: https://kubernetes.default.svc
        project: default
        source:
          path: argocd-apps
          repoURL: https://github.com/Antfield-Creations/gke.git
        syncPolicy:
          automated:
            selfHeal: true
            prune: true

  configs:
    repositories:
      antfield-helm-repo:
        type: git
        url: https://github.com/Antfield-Creations/gke
        path: charts
      argo-helm:
        type: helm
        url: https://argoproj.github.io/argo-helm
